services:
  node_app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node_app

volumes:
  mongodb_data:
